// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNgw4-KhUnVyrpMGRmG_XZndFKpIacphw',
    appId: '1:240567553752:web:79c401ff4efb153c6c51ad',
    messagingSenderId: '240567553752',
    projectId: 'crabproject-7c76f',
    authDomain: 'crabproject-7c76f.firebaseapp.com',
    storageBucket: 'crabproject-7c76f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABw7Yb7YcO1Mn3lIJFdx2fUEFGHd2clNg',
    appId: '1:240567553752:android:e2cd6e5617b01e266c51ad',
    messagingSenderId: '240567553752',
    projectId: 'crabproject-7c76f',
    storageBucket: 'crabproject-7c76f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmREshDKBGc0V85WxJfB5r9JA4kqhCAps',
    appId: '1:240567553752:ios:e3789f5f61477ed86c51ad',
    messagingSenderId: '240567553752',
    projectId: 'crabproject-7c76f',
    storageBucket: 'crabproject-7c76f.firebasestorage.app',
    iosBundleId: 'com.example.aqualyze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmREshDKBGc0V85WxJfB5r9JA4kqhCAps',
    appId: '1:240567553752:ios:e3789f5f61477ed86c51ad',
    messagingSenderId: '240567553752',
    projectId: 'crabproject-7c76f',
    storageBucket: 'crabproject-7c76f.firebasestorage.app',
    iosBundleId: 'com.example.aqualyze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNgw4-KhUnVyrpMGRmG_XZndFKpIacphw',
    appId: '1:240567553752:web:5b439f2008b2f42e6c51ad',
    messagingSenderId: '240567553752',
    projectId: 'crabproject-7c76f',
    authDomain: 'crabproject-7c76f.firebaseapp.com',
    storageBucket: 'crabproject-7c76f.firebasestorage.app',
  );
}